name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/java-docker

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверяем код
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Логин в GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Шаг 3: Сборка Docker образа
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      # Шаг 4: Пуш Docker образа
      - name: Push Docker image
        run: docker push $IMAGE_NAME:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/java-docker:latest

            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            docker stop java-app || true
            docker rm java-app || true
            docker pull $IMAGE_NAME
            docker run -d --name java-app -p 8080:8080 $IMAGE_NAME
